<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <ProjectReference Include="../../src/Depkeeper.Cli/Depkeeper.Cli.csproj" />
  </ItemGroup>
</Project>
